// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/business" | "/business/analytics" | "/business/campaigns" | "/business/campaigns/create" | "/business/earnings" | "/business/profile" | "/business/redeem" | "/business/redemptions" | "/business/settings" | "/business/transaction" | "/c/[token]" | "/creator" | "/creator/analytics" | "/creator/campaigns/available" | "/creator/campaigns/joined" | "/creator/earnings" | "/creator/match" | "/creator/profile" | "/creator/qr" | "/creator/settings" | "/creator/transaction" | "/demo/match" | "/forgot-password" | "/login" | "/register"
type PageRoutes = never
type LayoutRoutes = "/" | "/business" | "/creator"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/business": {}
  "/business/analytics": {}
  "/business/campaigns": {}
  "/business/campaigns/create": {}
  "/business/earnings": {}
  "/business/profile": {}
  "/business/redeem": {}
  "/business/redemptions": {}
  "/business/settings": {}
  "/business/transaction": {}
  "/c/[token]": { "token": string; }
  "/creator": {}
  "/creator/analytics": {}
  "/creator/campaigns/available": {}
  "/creator/campaigns/joined": {}
  "/creator/earnings": {}
  "/creator/match": {}
  "/creator/profile": {}
  "/creator/qr": {}
  "/creator/settings": {}
  "/creator/transaction": {}
  "/demo/match": {}
  "/forgot-password": {}
  "/login": {}
  "/register": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/business": never
  "/creator": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
